---
- name: Task 4 Configure SSH Server
  hosts: all
  become: true
  vars:
    ssh_path: "/etc/ssh/sshd_config"
  tasks:
    - name: Set Banner
      lineinfile:
        path: "{{ ssh_path }}"
        regexp: '^#Banner'
        line: 'Banner /etc/motd'
      register: output1

    - name: Disabling X11 Forwarding
      lineinfile:
        path: "{{ ssh_path }}"
        regexp: '^X11Forwarding yes'
        line: 'X11Forwarding no'
      register: output2
    
    - name: Set MaxAuthTries to 3
      lineinfile:
        path: "{{ ssh_path }}"
        regexp: 'MaxAuthTries'
        line: 'MaxAuthTries 3'
      register: output3

    - name: Applying SSHD changes
      service:
        name: sshd
        state: restarted
#      when: output1['changed'] == true or output2['changed'] == true or output3['changed'] == true
