---
- name: Task 13 Use Conditionals to Control Play Execution
  hosts: all
  become: true
  tasks:
    - name: Set vm.swappiness to 10
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: ansible_facts['memtotal_mb'] > 2048

    - name: Show Messaging error
      debug:
        msg: "Service memory less than 2048MB"
      when: ansible_facts['memtotal_mb'] < 2048

        
