---
- name: task 17 Services
  hosts: webservers
  become: true
  tasks:
    - name: Get current systemd default
      command: "systemctl get-default"
      changed_when: false
      register: getdefault

    - name: Set Default boot target to multi-user
      file:
        src: /usr/lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target
        state: link
      when: "'multi-user.target' != getdefault.stdout"   


