---
- name: Task 6 Users and Groups
  hosts: all
  become: true
  vars_files:
   - ~/plays/vars/user_list.yml
   - ~/plays/secret.yml
  tasks:
    - name: Create Users webservers
      user:
          name: "{{ item['username'] }}"
          uid: "{{ item['uid'] }}"
          password: "{{ user_password | password_hash('sha512') }}"
          update_password: on_create
          shell: /bin/bash
          groups: wheel
          append: true
      when: 
      - "'webservers' in group_names" 
      - (item['uid'] | string)[0] | int == 1 
      loop: "{{ users }}"

    - name: Create Users database
      user:
          name: "{{ item['username'] }}"
          uid: "{{ item['uid'] }}"
          password: "{{ user_password | password_hash('sha512') }}"
          update_password: on_create
          shell: /bin/bash
          groups: wheel
          append: true
      when: 
      - "'database' in group_names" 
      - (item['uid'] | string)[0] | int == 2 
      loop: "{{ users }}"

    - name: Transfer SSH
      authorized_key:
          user: "{{ item['username'] }}"
          state: present
          key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
      when: ("'webservers' in group_names" and (item['uid'] | string)[0] | int == 1) or 
            ("'database' in group_names" and (item['uid'] | string)[0] | int == 2)
      loop: "{{ users }}"



